### ISSUE TITLE
Замечания по lw2/task2

### ISSUE THREAD

**Issue by ivklgn** [SofronovMichail/web-development-course#3]
стили кнопок далеки от примера в задании, сделайте более похожими
размеры не соответствуют макету

--------

**background color у кнопок по макету не серый**

**Comment by lulldev** [comment]
```html
    <!-- XLarge Default buttons -->
    <button class="button-large">XLarge Default</button>
    <button class="button-large button-filled">XLarge Default</button>
    <button class="button button-large">XLarge Default</button>
    <button class="button button-large button-filled">XLarge Default</button>
    <button class="button button-large button-rounded">XLarge Default</button>
    <button class="button button-large button-filled button-rounded">XLarge Default</button>

    <br>
```

не используйте `<br>`. лучше для строки набора кнопок сделать служебный класс

```html
    <!-- XLarge Default buttons -->
<div class="buttons-group">
    <button class="button-large">XLarge Default</button>
    <button class="button-large button-filled">XLarge Default</button>
    <button class="button button-large">XLarge Default</button>
    <button class="button button-large button-filled">XLarge Default</button>
    <button class="button button-large button-rounded">XLarge Default</button>
    <button class="button button-large button-filled button-rounded">XLarge Default</button>
</div>
```

**Comment by lulldev** [comment]
```css
button {
  margin: 1%;
  border-radius: 0;
  padding: 10px 5px;
  font-size: 0.8em;
}
```

- не стилизуйте по тегу, нужно только по классу button
- margin: 1% - динамическая штука, не советую

**Comment by lulldev** [comment]
```css
.button-rounded {
  border-radius: 20px;
}

.button-large {
  font-size: 1em;
  color: dimgray;
  background-color: white;
}
```

данные классы не должны быть в отрыве от button:

```css
.button.button-rounded {
...
}

.button.button-large {
...
}
```
