### ISSUE TITLE
Замечания по lw3/task1

### ISSUE THREAD

**Issue by lulldev** [SofronovMichail/web-development-course#4]
```css
.title-description {
  width: 45%;
}
.title-size {
  width: 7%;
}
.title-price {
  width: 13%;
}
```

используйте пиксели вместо процентов

в других классах то же самое

**Comment by lulldev** [comment]
```css
@font-face {
  font-family: "Work Sans Medium";
  src: url(/task1/fonts/WorkSans-Medium.ttf);
}
@font-face {
  font-family: "Work Sans Light";
  src: url(/task1/fonts/WorkSans-Light.ttf);
}
```

используйте относительные пути: `fonts/WorkSans-Light.ttf`
